apiVersion: batch/v1
kind: Job
metadata:
  name: sarscovawa-job
spec:
  template:
    spec:
      containers:
      - name: sarscovawa-job
        image: yash5090/sarscovawa:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
