apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarscovawa-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: sarscovawa
  template:
    metadata:
      labels:
        app: sarscovawa
    spec:
      containers:
        - name: sarscovawa
          image: yash5090/sarscovawa:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
